name: first workflow
on:
 workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job variable"
    steps:
       - name: firstJob script
         shell: bash
         run: echo Hello World! This is the first job
       
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Greetings
         uses: actions/hello-world-javascript-action@main
         with:
           who-to-greet: 'Mona the Octocat'
       
       - name: time
         run: |
           echo "The time of the greeting was at: ${{ steps.Greetings.outputs.time }}"
  
  secondjob:
     runs-on: ubuntu-latest
     needs: firstjob
     env:
       JOB_VAR: "This is a job variable"
     steps:
        - name: secondJob script
          shell: bash
          run: |
            echo this is the second job
            echo and this is a multi-line script
